### ISSUE TITLE
Error while installing "homepage LXC"

### ISSUE THREAD

**Issue by Ancalgon** [tteck/Proxmox#1273]
I'd tried to change parameters or to force install vie ssh into the lxc but the problem persist

```
Downloading registry.npmjs.org/typescript/4.9.5: 11.6 MB/11.6 MB, done
node_modules/.pnpm/cpu-features@0.0.4/node_modules/cpu-features: Running install script, failed in 124ms (skipped as optional)
node_modules/.pnpm/core-js@3.29.1/node_modules/core-js: Running postinstall script, done in 127ms
node_modules/.pnpm/osx-temperature-sensor@1.0.8/node_modules/osx-temperature-sensor: Running install script, failed in 984ms
.../node_modules/osx-temperature-sensor install$ node-gyp rebuild
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@9.3.1
│ gyp info using node@16.19.1 | linux | x64
│ gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
│ gyp http GET https://nodejs.org/download/release/v16.19.1/node-v16.19.1-headers.tar.gz
│ gyp http 200 https://nodejs.org/download/release/v16.19.1/node-v16.19.1-headers.tar.gz
│ gyp http GET https://nodejs.org/download/release/v16.19.1/SHASUMS256.txt
│ gyp http 200 https://nodejs.org/download/release/v16.19.1/SHASUMS256.txt
│ gyp info spawn /usr/bin/python3
│ gyp info spawn args [
│ gyp info spawn args   '/usr/lib/node_modules/pnpm/dist/node_modules/node-gyp/gyp/gyp_main.py',
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'make',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/opt/homepage/node_modules/.pnpm/osx-temperature-sensor@1.0.8/node_modules/osx-temperature-sensor/build/config.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/usr/lib/node_modules/pnpm/dist/node_modules/node-gyp/addon.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/root/.cache/node-gyp/16.19.1/include/node/common.gypi',
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.19.1',
│ gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/pnpm/dist/node_modules/node-gyp',
│ gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.19.1/<(target_arch)/node.lib',
│ gyp info spawn args   '-Dmodule_root_dir=/opt/homepage/node_modules/.pnpm/osx-temperature-sensor@1.0.8/node_modules/osx-temperature-sensor',
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ gyp ERR! build error 
│ gyp ERR! stack Error: not found: make
│ gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/pnpm/dist/node_modules/which/which.js:10:17)
│ gyp ERR! stack     at /usr/lib/node_modules/pnpm/dist/node_modules/which/which.js:57:18
│ gyp ERR! stack     at new Promise (<anonymous>)
│ gyp ERR! stack     at step (/usr/lib/node_modules/pnpm/dist/node_modules/which/which.js:54:21)
│ gyp ERR! stack     at /usr/lib/node_modules/pnpm/dist/node_modules/which/which.js:71:22
│ gyp ERR! stack     at new Promise (<anonymous>)
│ gyp ERR! stack     at subStep (/usr/lib/node_modules/pnpm/dist/node_modules/which/which.js:69:33)
│ gyp ERR! stack     at /usr/lib/node_modules/pnpm/dist/node_modules/which/which.js:80:22
│ gyp ERR! stack     at /usr/lib/node_modules/pnpm/dist/node_modules/isexe/index.js:42:5
│ gyp ERR! stack     at /usr/lib/node_modules/pnpm/dist/node_modules/isexe/mode.js:8:5
│ gyp ERR! System Linux 5.15.102-1-pve
│ gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
│ gyp ERR! cwd /opt/homepage/node_modules/.pnpm/osx-temperature-sensor@1.0.8/node_modules/osx-temperature-sensor
│ gyp ERR! node -v v16.19.1
│ gyp ERR! node-gyp -v v9.3.1
│ gyp ERR! not ok 
└─ Failed in 984ms at /opt/homepage/node_modules/.pnpm/osx-temperature-sensor@1.0.8/node_modules/osx-temperature-sensor
Progress: resolved 468, reused 0, downloaded 468, added 468, done
 ELIFECYCLE  Command failed with exit code 1.
++ error_handler 37 '$STD pnpm install'
++ local exit_code=1
++ local line_number=37
++ local 'command=$STD pnpm install'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m37\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD pnpm install\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m37\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD pnpm install\033[m\n'

[ERROR] in line 37: exit code 1: while executing command $STD pnpm install

+ exit
```

**Comment by tteck** [comment]
It appears that the issues are caused by commits that were made 10 hours ago.

**Comment by tteck** [comment]
Fixed
