### ISSUE TITLE
Update of Homepage fails

### ISSUE THREAD

**Issue by phellarv** [tteck/Proxmox#1288]
When I try to update Homepage, it fails

Log (with set -x):
+ cat
    __  __                                          
   / / / /___  ____ ___  ___  ____  ____ _____ ____ 
  / /_/ / __ \/ __ `__ \/ _ \/ __ \/ __ `/ __ `/ _ \
 / __  / /_/ / / / / / /  __/ /_/ / /_/ / /_/ /  __/
/_/ /_/\____/_/ /_/ /_/\___/ .___/\__,_/\__, /\___/ 
                          /_/          /____/       
+ [[ ! -d /opt/homepage ]]
+ msg_info 'Updating Homepage'
+ local 'msg=Updating Homepage'
+ echo -ne ' - \033[33mUpdating Homepage...'
 - Updating Homepage...+ command -v pnpm
+ cd /opt/homepage
+ systemctl stop homepage
+ git pull --force
+ pnpm install
++ error_handler 64 'pnpm install &> /dev/null'
++ local exit_code=1
++ local line_number=64
++ local 'command=pnpm install &> /dev/null'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m64\033[m: exit code \033[01;31m1\033[m: while executing command \033[33mpnpm install &> /dev/null\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m64\033[m: exit code \033[01;31m1\033[m: while executing command \033[33mpnpm install &> /dev/null\033[m\n'

[ERROR] in line 64: exit code 1: while executing command pnpm install &> /dev/null

root@homepage:~# cd /opt/homepage/
root@homepage:/opt/homepage# git pull
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
root@homepage:/opt/homepage# systemctl start homepage
You have mail in /var/mail/root
root@homepage:/opt/homepage# systemctl stop homepage
root@homepage:/opt/homepage# pnpm install
 WARN  Ignoring broken lockfile at /opt/homepage: Lockfile /opt/homepage/pnpm-lock.yaml not compatible with current pnpm
 WARN  deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
 WARN  deprecated har-validator@5.1.5: this library is no longer supported
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Packages: +470
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 480, reused 468, downloaded 0, added 0, done
node_modules/.pnpm/cpu-features@0.0.4/node_modules/cpu-features: Running install script, failed in 181ms (skipped as optional)
node_modules/.pnpm/core-js@3.29.1/node_modules/core-js: Running postinstall script, done in 169ms
node_modules/.pnpm/osx-temperature-sensor@1.0.8/node_modules/osx-temperature-sensor: Running install script, failed in 2.9s
.../node_modules/osx-temperature-sensor install$ node-gyp rebuild
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@9.3.0
│ gyp info using node@14.21.3 | linux | x64
│ gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
│ gyp info spawn /usr/bin/python3
│ gyp info spawn args [
│ gyp info spawn args   '/usr/lib/node_modules/pnpm/dist/node_modules/node-gyp/gyp/gyp_main.py',
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'make',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/opt/homepage/node_modules/.pnpm/osx-temperature-sensor@1.0.8/node_modules/osx-temperature-sensor/build/config.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/usr/lib/node_modules/pnpm/dist/node_modules/node-gyp/addon.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/root/.cache/node-gyp/14.21.3/include/node/common.gypi',
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.21.3',
│ gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/pnpm/dist/node_modules/node-gyp',
│ gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.21.3/<(target_arch)/node.lib',
│ gyp info spawn args   '-Dmodule_root_dir=/opt/homepage/node_modules/.pnpm/osx-temperature-sensor@1.0.8/node_modules/osx-temperature-sensor',
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ gyp ERR! build error 
│ gyp ERR! stack Error: not found: make
│ gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/pnpm/dist/node_modules/which/which.js:10:17)
│ gyp ERR! stack     at /usr/lib/node_modules/pnpm/dist/node_modules/which/which.js:57:18
│ gyp ERR! stack     at new Promise (<anonymous>)
│ gyp ERR! stack     at step (/usr/lib/node_modules/pnpm/dist/node_modules/which/which.js:54:21)
│ gyp ERR! stack     at /usr/lib/node_modules/pnpm/dist/node_modules/which/which.js:71:22
│ gyp ERR! stack     at new Promise (<anonymous>)
│ gyp ERR! stack     at subStep (/usr/lib/node_modules/pnpm/dist/node_modules/which/which.js:69:33)
│ gyp ERR! stack     at /usr/lib/node_modules/pnpm/dist/node_modules/which/which.js:80:22
│ gyp ERR! stack     at /usr/lib/node_modules/pnpm/dist/node_modules/isexe/index.js:42:5
│ gyp ERR! stack     at /usr/lib/node_modules/pnpm/dist/node_modules/isexe/mode.js:8:5
│ gyp ERR! System Linux 5.15.85-1-pve
│ gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
│ gyp ERR! cwd /opt/homepage/node_modules/.pnpm/osx-temperature-sensor@1.0.8/node_modules/osx-temperature-sensor
│ gyp ERR! node -v v14.21.3
│ gyp ERR! node-gyp -v v9.3.0
│ gyp ERR! not ok 
└─ Failed in 2.9s
 ELIFECYCLE  Command failed with exit code 1.

**Comment by phellarv** [comment]
I've debugged down to that it needs:
`apt install -y make g++`

**Comment by phellarv** [comment]
But pnpm build still fails:
root@homepage:/opt/homepage# pnpm build

> startpage@0.1.0 build /opt/homepage
> next build

info  - Linting and checking validity of types  
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from /opt/homepage/.babelrc
info  - Creating an optimized production build .Killed

**Comment by phellarv** [comment]
I bumped from 1G to 2G RAM, and then it went through.
