### ISSUE TITLE
Problems with updating paperless-ngs

### ISSUE THREAD

**Issue by hellofaduck** [tteck/Proxmox#1394]
### A clear and concise description of the issue.

I have a problem with at least 3 or 4 of the latest versions.
The raw problem looks like this:
 _ Stopped Paperless-ngx
 - Updating to v1.14.4...
[ERROR] in line 83: exit code 1: while executing command pip install -r requirements.txt &> /dev/null`

I don't understand the root problem, some problem with OpenSSL? All packages on the system are up to date..
I understand it's not your script problem but maybe you are more experienced in that than me and can see problem quickly, thanks for the great scripts, use them in everyday work!

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

So I tried to reproduce your script step by step to see more about problem:
`Collecting zxing-cpp==2.0.0                                                                       [50/326]
  Using cached zxing-cpp-2.0.0.tar.gz (8.6 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3/dist-packages/pip install --ignore-installed --no-user --pre
fix /tmp/pip-build-env-lx6h9qzw/overlay --no-warn-script-location --no-binary :none: --only-binary :none:
-i https://pypi.python.org/simple --extra-index-url https://www.piwheels.org/simple -- 'setuptools>=42' se
tuptools_scm wheel 'cmake>=3.14'
       cwd: None
  Complete output (59 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/lib/python3/dist-packages/pip/__main__.py", line 16, in <module>
      from pip._internal.cli.main import main as _main  # isort:skip # noqa
    File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
      from pip._internal.cli.autocompletion import autocomplete
    File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
      from pip._internal.cli.main_parser import create_main_parser
    File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
      from pip._internal.cli import cmdoptions
    File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
      from pip._internal.exceptions import CommandError
    File "/usr/lib/python3/dist-packages/pip/_internal/exceptions.py", line 10, in <module>
      from pip._vendor.six import iteritems
    File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 65, in <module>
      vendored("cachecontrol")
    File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
      __import__(modulename, globals(), locals(), level=0)
      __import__(modulename, globals(), locals(), level=0)
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
    File "<frozen zipimport>", line 259, in load_module
    File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/__init__.py", lin
e 9, in <module>

    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
    File "<frozen zipimport>", line 259, in load_module
    File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/wrapper.py", line
 1, in <module>
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
    File "<frozen zipimport>", line 259, in load_module
    File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/adapter.py", line
 5, in <module>
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
    File "<frozen zipimport>", line 259, in load_module
    File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
    File "/usr/local/lib/python3.8/dist-packages/OpenSSL/__init__.py", line 8, in <module>
      from OpenSSL import SSL, crypto
    File "/usr/local/lib/python3.8/dist-packages/OpenSSL/SSL.py", line 19, in <module>
      from OpenSSL.crypto import (
    File "/usr/local/lib/python3.8/dist-packages/OpenSSL/crypto.py", line 3253, in <module>
      utils.deprecated(
  TypeError: deprecated() got an unexpected keyword argument 'name'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-lx6h9qzw/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.python.org/simple --extra-index-url https://www.piwheels.org/simple -- 'setuptools>=42' setuptools_scm wheel 'cmake>=3.14' Check the logs for full command output.

### Please provide detailed steps to reproduce the issue.

Just run the script to update

**Comment by tteck** [comment]
It does not pose a problem for me.
```
    ____                        __                                     
   / __ \____ _____  ___  _____/ /__  __________    ____  ____ __  __
  / /_/ / __ `/ __ \/ _ \/ ___/ / _ \/ ___/ ___/___/ __ \/ __ `/ |/_/
 / ____/ /_/ / /_/ /  __/ /  / /  __(__  |__  )___/ / / / /_/ />  <  
/_/    \__,_/ .___/\___/_/  /_/\___/____/____/   /_/ /_/\__, /_/|_|  
           /_/                                         /____/        
 
 ✓ Stopped Paperless-ngx
 ✓ paperless-task-queue.service Exists.
 ✓ Updated to v1.14.4
 ✓ Cleaned
 ✓ Started Paperless-ngx
 ✓ Updated Successfully!

root@paperless-ngx:~# 
```
Moving to discussions
