### ISSUE TITLE
OpenHAB 4.x requires Java 17

### ISSUE THREAD

**Issue by MLNW** [tteck/Proxmox#1734]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Installing OpenHAB with the install script succeeds but the instance does not start up. This is due to the [new requirement](https://www.openhab.org/docs/installation/#prerequisites) for Java 17 on the host system for OpenHAB 4.x.

This is the error message provided:

```
Aug 26 17:26:00 openhab systemd[1]: Started openHAB - empowering the smart home.
Aug 26 17:26:19 openhab karaf[12843]: org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-runtime-ui; type=karaf.feature; version="[4.0.2,4.0.2]"; fi>
Aug 26 17:26:19 openhab karaf[12843]:         at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
Aug 26 17:26:19 openhab karaf[12843]:         at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:433)
Aug 26 17:26:19 openhab karaf[12843]:         at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:420)
Aug 26 17:26:19 openhab karaf[12843]:         at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:374)
Aug 26 17:26:19 openhab karaf[12843]:         at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:256)
Aug 26 17:26:19 openhab karaf[12843]:         at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399)
Aug 26 17:26:19 openhab karaf[12843]:         at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
Aug 26 17:26:19 openhab karaf[12843]:         at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
Aug 26 17:26:19 openhab karaf[12843]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Aug 26 17:26:19 openhab karaf[12843]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Aug 26 17:26:19 openhab karaf[12843]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Aug 26 17:26:19 openhab karaf[12843]:         at java.base/java.lang.Thread.run(Thread.java:829)
Aug 26 17:26:19 openhab karaf[12843]: Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve openhab-runtime-ui/4.0.2: missing requirement [openhab-runtime-ui/4.0.2] osgi.identity; osgi.identity=openhab-runtime->
Aug 26 17:26:19 openhab karaf[12843]:         at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
Aug 26 17:26:19 openhab karaf[12843]:         ... 12 more
Aug 26 17:26:19 openhab karaf[12843]: Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve openhab-runtime-base/4.0.2: missing requirement [openhab-runtime-base/4.0.2] osgi.identity; osgi.identity=openhab-core>
Aug 26 17:26:19 openhab karaf[12843]:         at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
Aug 26 17:26:19 openhab karaf[12843]:         ... 13 more
Aug 26 17:26:19 openhab karaf[12843]: Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve openhab-core-base/4.0.2: missing requirement [openhab-core-base/4.0.2] osgi.identity; osgi.identity=org.openhab.core.c>
Aug 26 17:26:19 openhab karaf[12843]:         at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
Aug 26 17:26:19 openhab karaf[12843]:         ... 14 more
Aug 26 17:26:19 openhab karaf[12843]: Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.openhab.core.config.core/4.0.2: missing requirement [org.openhab.core.config.core/4.0.2] osgi.wiring.package; filt>
Aug 26 17:26:19 openhab karaf[12843]:         at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
Aug 26 17:26:19 openhab karaf[12843]:         ... 15 more
Aug 26 17:26:19 openhab karaf[12843]: Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve org.openhab.core/4.0.2: missing requirement [org.openhab.core/4.0.2] osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=17))"
Aug 26 17:26:19 openhab karaf[12843]:         at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
Aug 26 17:26:19 openhab karaf[12843]:         ... 16 more
```

After installing Java 17 and restarting the service OpenHAB boots up correctly.

### Which Linux distribution are you employing?

Ubuntu 22.04

**Comment by tteck** [comment]
Fixed, thanks for reporting!

```
openjdk version "17.0.8" 2023-07-18 LTS
OpenJDK Runtime Environment Zulu17.44+15-CA (build 17.0.8+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.44+15-CA (build 17.0.8+7-LTS, mixed mode, sharing)
```
