### ISSUE TITLE
Error installing Change Detection LXC - /opt/browserless fails

### ISSUE THREAD

**Issue by ndbroadbent** [tteck/Proxmox#1749]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

The Change Detection LXC setup script is now failing. It worked when I ran it earlier today, so I think it might have just broken.

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

Logs:

```
 ✓ Installed Change Detection
+ msg_info 'Installing Browserless & Playwright'
+ local 'msg=Installing Browserless & Playwright'
+ echo -ne ' - \033[33mInstalling Browserless & Playwright...'
 - Installing Browserless & Playwright...+ mkdir /opt/browserless
+ python3 -m pip install playwright
Collecting playwright
  Downloading playwright-1.37.0-py3-none-manylinux1_x86_64.whl (35.7 MB)
     |████████████████████████████████| 35.7 MB 84.0 MB/s 
Collecting pyee==9.0.4
  Downloading pyee-9.0.4-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: greenlet==2.0.2 in /usr/local/lib/python3.9/dist-packages (from playwright) (2.0.2)
Collecting typing-extensions
  Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Installing collected packages: typing-extensions, pyee, playwright
Successfully installed playwright-1.37.0 pyee-9.0.4 typing-extensions-4.7.1
+ git clone https://github.com/browserless/chrome /opt/browserless
Cloning into '/opt/browserless'...
remote: Enumerating objects: 18043, done.
remote: Counting objects: 100% (4087/4087), done.
remote: Compressing objects: 100% (122/122), done.
remote: Total 18043 (delta 4044), reused 3989 (delta 3965), pack-reused 13956
Receiving objects: 100% (18043/18043), 93.35 MiB | 9.07 MiB/s, done.
Resolving deltas: 100% (13866/13866), done.
+ npm install --prefix /opt/browserless

> browserless-chrome@1.59.0 postinstall
> node ./scripts/postinstall.js

HIT false
Downloading chromium for revision 116.0.5845.96
Downloading chromedriver for revision 116.0.5845.96
Downloading devtools assets for revision 116.0.5845.96
Downloading ad-blocking list
Error unpacking assets:
Error: end of central directory record signature not found
    at /opt/browserless/node_modules/yauzl/index.js:187:14
    at /opt/browserless/node_modules/yauzl/index.js:631:5
    at /opt/browserless/node_modules/fd-slicer/index.js:32:7
    at FSReqCallback.wrapper [as oncomplete] (node:fs:684:5)
npm notice 
npm notice New major version of npm available! 9.6.7 -> 10.0.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.0.0
npm notice Run npm install -g npm@10.0.0 to update!
npm notice 
npm ERR! code 1
npm ERR! path /opt/browserless
npm ERR! command failed
npm ERR! command sh -c node ./scripts/postinstall.js

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-09-01T10_18_34_449Z-debug-0.log
++ error_handler 72 '$STD npm install --prefix /opt/browserless'
++ local exit_code=1
++ local line_number=72
++ local 'command=$STD npm install --prefix /opt/browserless'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m72\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD npm install --prefix /opt/browserless\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m72\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD npm install --prefix /opt/browserless\033[m'

[ERROR] in line 72: exit code 1: while executing command $STD npm install --prefix /opt/browserless
++ [[ 72 -eq 24 ]]
+ exit
root@proxmox:~# 
```

### Please provide detailed steps to reproduce the issue.

Run Change Detection LXC script

**Comment by ndbroadbent** [comment]
Whoever broke it seems to have just fixed it. I opened the console for the container and ran it again manually. It failed again with the same error, but now it is passing:

```
root@changedetection:/opt/browserless# npm install --prefix /opt/browserless

> browserless-chrome@1.59.0 postinstall
> node ./scripts/postinstall.js

HIT false
Downloading chromium for revision 116.0.5845.96
Downloading chromedriver for revision 116.0.5845.96
Downloading devtools assets for revision 116.0.5845.96
Downloading ad-blocking list
Done unpacking chromedriver and devtools assets

up to date, audited 864 packages in 27s

133 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (2 moderate, 1 critical)

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
root@changedetection:/opt/browserless# 
```

Maybe just a problem with NPM or something else was down for a while.
