### ISSUE TITLE
MagicMirror Server Fails at End

### ISSUE THREAD

**Issue by esmoyer** [tteck/Proxmox#1911]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Running the MagicMirror Server script results in an error; everything seems to go fine until the very end. The only options I changed were the IP and Gateway addresses. Tried both as Priv and Unpriv container.

Not sure if related to: https://github.com/tteck/Proxmox/issues/377

### Which Linux distribution are you employing?

Debian 11

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

NODE LOG - Verbose
```
 ✓ Set up MagicMirror Repository
+ msg_info 'Installing MagicMirror'
+ local 'msg=Installing MagicMirror'
+ echo -ne ' - \033[33mInstalling MagicMirror...'
 - Installing MagicMirror...+ cd /opt/magicmirror
+ npm install --only=prod --omit=dev
npm WARN config only Use `--omit=dev` to omit dev dependencies from the install.
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: magicmirror@2.25.0
npm ERR! notsup Not compatible with your version of node/npm: magicmirror@2.25.0
npm ERR! notsup Required: {"node":">=18"}
npm ERR! notsup Actual:   {"npm":"8.19.4","node":"v16.20.1"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-10-12T16_06_47_161Z-debug-0.log
++ error_handler 36 '$STD npm install --only=prod --omit=dev'
++ local exit_code=1
++ local line_number=36
++ local 'command=$STD npm install --only=prod --omit=dev'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m36\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD npm install --only=prod --omit=dev\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m36\033[m: exit code \033[01;31m1\033[m: while executing command \033[33m$STD npm install --only=prod --omit=dev\033[m'

[ERROR] in line 36: exit code 1: while executing command $STD npm install --only=prod --omit=dev
++ [[ 36 -eq 24 ]]
+ exit
```

CONTAINER LOG (as referenced from above error)
```
root@magicmirrorlxc:~/.npm/_logs# cat 2023-10-12T16_06_47_161Z-debug-0.log 
0 verbose cli /root/.nvm/versions/node/v16.20.1/bin/node /root/.nvm/versions/node/v16.20.1/bin/npm
1 info using npm@8.19.4
2 info using node@v16.20.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/root/.nvm/versions/node/v16.20.1/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 warn config only Use `--omit=dev` to omit dev dependencies from the install.
8 timing config:load:cli Completed in 2ms
9 timing config:load:env Completed in 1ms
10 timing config:load:file:/opt/magicmirror/.npmrc Completed in 1ms
11 timing config:load:project Completed in 1ms
12 timing config:load:file:/root/.npmrc Completed in 1ms
13 timing config:load:user Completed in 1ms
14 timing config:load:file:/root/.nvm/versions/node/v16.20.1/etc/npmrc Completed in 0ms
15 timing config:load:global Completed in 0ms
16 timing config:load:validate Completed in 0ms
17 timing config:load:credentials Completed in 1ms
18 timing config:load:setEnvs Completed in 1ms
19 timing config:load Completed in 10ms
20 timing npm:load:configload Completed in 10ms
21 timing npm:load:mkdirpcache Completed in 0ms
22 timing npm:load:mkdirplogs Completed in 1ms
23 verbose title npm install
24 verbose argv "install" "--only" "prod" "--omit" "dev"
25 timing npm:load:setTitle Completed in 1ms
26 timing config:load:flatten Completed in 2ms
27 timing npm:load:display Completed in 5ms
28 verbose logfile logs-max:10 dir:/root/.npm/_logs
29 verbose logfile /root/.npm/_logs/2023-10-12T16_06_47_161Z-debug-0.log
30 timing npm:load:logFile Completed in 4ms
31 timing npm:load:timers Completed in 0ms
32 timing npm:load:configScope Completed in 0ms
33 timing npm:load Completed in 22ms
34 timing arborist:ctor Completed in 1ms
35 silly logfile done cleaning log files
36 timing idealTree:init Completed in 972ms
37 timing idealTree:userRequests Completed in 0ms
38 silly idealTree buildDeps
39 timing idealTree:#root Completed in 0ms
40 timing idealTree:buildDeps Completed in 2ms
41 timing idealTree:fixDepFlags Completed in 0ms
42 timing idealTree Completed in 978ms
43 timing command:install Completed in 1029ms
44 verbose stack Error: Unsupported engine
44 verbose stack     at checkEngine (/root/.nvm/versions/node/v16.20.1/lib/node_modules/npm/node_modules/npm-install-checks/lib/index.js:14:25)
44 verbose stack     at Arborist.[checkEngineAndPlatform] (/root/.nvm/versions/node/v16.20.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:228:11)
44 verbose stack     at Arborist.buildIdealTree (/root/.nvm/versions/node/v16.20.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:214:42)
44 verbose stack     at async Promise.all (index 1)
44 verbose stack     at async Arborist.reify (/root/.nvm/versions/node/v16.20.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:154:5)
44 verbose stack     at async Install.exec (/root/.nvm/versions/node/v16.20.1/lib/node_modules/npm/lib/commands/install.js:145:5)
44 verbose stack     at async module.exports (/root/.nvm/versions/node/v16.20.1/lib/node_modules/npm/lib/cli.js:78:5)
45 verbose pkgid magicmirror@2.25.0
46 verbose cwd /opt/magicmirror
47 verbose Linux 5.15.116-1-pve
48 verbose node v16.20.1
49 verbose npm  v8.19.4
50 error code EBADENGINE
51 error engine Unsupported engine
52 error engine Not compatible with your version of node/npm: magicmirror@2.25.0
53 error notsup Not compatible with your version of node/npm: magicmirror@2.25.0
53 error notsup Required: {"node":">=18"}
53 error notsup Actual:   {"npm":"8.19.4","node":"v16.20.1"}
54 verbose exit 1
55 timing npm Completed in 1197ms
56 verbose unfinished npm timer reify 1697126807325
57 verbose unfinished npm timer reify:loadTrees 1697126807374
58 verbose code 1
59 error A complete log of this run can be found in:
59 error     /root/.npm/_logs/2023-10-12T16_06_47_161Z-debug-0.log
root@magicmirrorlxc:~/.npm/_logs# 
```

### Please provide detailed steps to reproduce the issue.

1. Run the script
2. Change IP from DHCP to static CIDR
3. Change Gateway IP
4. Let run
5. Error happens

**Comment by tteck** [comment]
Fixed

**Comment by esmoyer** [comment]
You're amazing! Thanks!
