### ISSUE TITLE
 Paperless-ngx LXC script - [ERROR] in line 24: exit code 2: while executing command "$@" > /dev/null 2>&1

### ISSUE THREAD

**Issue by runben** [tteck/Proxmox#1950]
Hi ,I got this error when i was trying to create Paperless-ngx in Proxmox shell via this command:
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/paperless-ngx.sh)"

Creating a Paperless-ngx LXC using the above advanced settings
✓ Using local for Template Storage.
✓ Using local-lvm for Container Storage.
✓ Updated LXC Template List
✓ LXC Container 215 was successfully created.
✓ Started LXC Container
✓ Set up Container OS
✓ Network Connected: 192.168.0.44
✓ Internet Connected
✓ DNS Resolved github.com to 20.233.83.145
✓ Updated Container OS
✓ Installed Python3
✓ Installed Dependencies
✓ Installed OCR Dependencies
✓ Installed JBIG2

Installing Paperless-ngx (Patience)...
[ERROR] in line 24: exit code 2: while executing command "$@" > /dev/null 2>&1
The silent function has suppressed the error, run the script with verbose mode enabled, which will provide more detailed output.
Verbose Mode:

Downloading numpy-1.24.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━ 9.4/17.3 MB 39.7 MB/s eta 0:00:01
ERROR: Exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
yield
File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/urllib3/response.py", line 561, in read
data = self._fp_read(amt) if not fp_closed else b""
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
return self._fp.read(amt) if amt is not None else self._fp.read()
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/cachecontrol/filewrapper.py", line 98, in read
data: bytes = self.__fp.read(amt)
^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/http/client.py", line 465, in read
s = self.fp.read(amt)
^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/socket.py", line 706, in readinto
return self._sock.recv_into(b)
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/ssl.py", line 1278, in recv_into
return self.read(nbytes, buffer)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/ssl.py", line 1134, in read
return self._sslobj.read(len, buffer)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.11/dist-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
status = run_func(*args)
^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
return func(self, options, args)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/pip/_internal/commands/install.py", line 377, in run
requirement_set = resolver.resolve(
^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 179, in resolve
self.factory.preparer.prepare_linked_requirements_more(reqs)
File "/usr/local/lib/python3.11/dist-packages/pip/_internal/operations/prepare.py", line 552, in prepare_linked_requirements_more
self._complete_partial_requirements(
File "/usr/local/lib/python3.11/dist-packages/pip/_internal/operations/prepare.py", line 467, in _complete_partial_requirements
for link, (filepath, _) in batch_download:
File "/usr/local/lib/python3.11/dist-packages/pip/_internal/network/download.py", line 183, in call
for chunk in chunks:
File "/usr/local/lib/python3.11/dist-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
for chunk in iterable:
File "/usr/local/lib/python3.11/dist-packages/pip/_internal/network/utils.py", line 63, in response_chunks
for chunk in response.raw.stream(
File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/urllib3/response.py", line 622, in stream
data = self.read(amt=amt, decode_content=decode_content)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/urllib3/response.py", line 560, in read
with self._error_catcher():
File "/usr/lib/python3.11/contextlib.py", line 155, in exit
self.gen.throw(typ, value, traceback)
File "/usr/local/lib/python3.11/dist-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
++ error_handler 88 '$STD pip install -r requirements.txt'
++ local exit_code=2
++ local line_number=88
++ local 'command=$STD pip install -r requirements.txt'
++ local 'error_message=\033[01;31m[ERROR]\033[m in line \033[01;31m88\033[m: exit code \033[01;31m2\033[m: while executing command \033[33m$STD pip install -r requirements.txt\033[m'
++ echo -e '\n\033[01;31m[ERROR]\033[m in line \033[01;31m88\033[m: exit code \033[01;31m2\033[m: while executing command \033[33m$STD pip install -r requirements.txt\033[m'

[ERROR] in line 88: exit code 2: while executing command $STD pip install -r requirements.txt
++ [[ 88 -eq 24 ]]

exit
Can you please tell me what I am doing wrong? I gave 20GB disk space, just FYI.

**Comment by tteck** [comment]
The script runs without any problems from this end. 

```
    ____                        __                                     
   / __ \____ _____  ___  _____/ /__  __________    ____  ____ __  __
  / /_/ / __ `/ __ \/ _ \/ ___/ / _ \/ ___/ ___/___/ __ \/ __ `/ |/_/
 / ____/ /_/ / /_/ /  __/ /  / /  __(__  |__  )___/ / / / /_/ />  <  
/_/    \__,_/ .___/\___/_/  /_/\___/____/____/   /_/ /_/\__, /_/|_|  
           /_/                                         /____/        
 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 12
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: paperless-ngx
Using Disk Size: 10
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Paperless-ngx LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.113.3
 ✓ Updated Container OS
 ✓ Installed Python3
 ✓ Installed Dependencies
 ✓ Installed OCR Dependencies
 ✓ Installed JBIG2
 ✓ Installed Paperless-ngx
 ✓ Installed Natural Language Toolkit
 ✓ Set up PostgreSQL database
Would you like to add Adminer? <y/N> 
 ✓ Set up admin Paperless-ngx User & Password
 ✓ Created Services
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Paperless-ngx should be reachable by going to the following URL.
         http://192.168.86.253:8000 
```

**Comment by tteck** [comment]
Try increasing RAM. 🤷🏻‍♂️

**Comment by tteck** [comment]
As this issue is unrelated to the script, it is considered closed.
