### ISSUE TITLE
Deluged failing to start on Debian 12

### ISSUE THREAD

**Issue by Drallas** [tteck/Proxmox#1972]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Installed Deluged when I choose Debian 12 Bookworm the WebGui is inactive and the service dead! (Tried to install 2 times)

System Status error:
`SystemError: initialization of libtorrent raised unreported exception`

Same install Debian 11 Deluge works fine. 

### Which Linux distribution are you employing?

Debian 12

### If relevant, including screenshots or a code block can be helpful in clarifying the issue.

```
root@deluge:~# systemctl status deluged
x deluged.service - Deluge Bittorrent Client Daemon
Loaded: loaded (/etc/systemd/system/deluged.service; enabled; preset: enabled)
Active: failed (Result: exit-code) since Sat 2023-10-28 12:20:13 CEST; 2min 9s ago
Duration: 162ms
Docs: man:deluged
Process: 354 ExecStart=/usr/local/bin/deluged -d (code=exited, status=1/FAILURE)
Main PID: 354 (code=exited, status=1/FAILURE)
CPU: 160ms

Oct 28 12:20:13 deluge systemd[1]: deluged.service: Scheduled restart job, restart counter is >
Oct 28 12:20:13 deluge systemd[1]: Stopped deluged.service - Deluge Bittorrent Client Daemon.
Oct 28 12:20:13 deluge systemd[1]: deluged.service: Start request repeated too quickly.
Oct 28 12:20:13 deluge systemd[1]: deluged.service: Failed with result 'exit-code'.
Oct 28 12:20:13 deluge systemd[1]: Failed to start deluged.service - Deluge Bittorrent Client

Oct 28 12:20:13 deluge deluged[354]: Traceback (most recent call last):
Oct 28 12:20:13 deluge deluged[354]:   File "/usr/local/bin/deluged", line 8, in <module>
Oct 28 12:20:13 deluge deluged[354]:     sys.exit(start_daemon())
Oct 28 12:20:13 deluge deluged[354]:              ^^^^^^^^^^^^^^
Oct 28 12:20:13 deluge deluged[354]:   File "/usr/local/lib/python3.11/dist-packages/deluge/core/daemon_entry.py", line 81, in start_daemon
Oct 28 12:20:13 deluge deluged[354]:     parser = ArgParserBase()
Oct 28 12:20:13 deluge deluged[354]:              ^^^^^^^^^^^^^^^
Oct 28 12:20:13 deluge deluged[354]:   File "/usr/local/lib/python3.11/dist-packages/deluge/argparserbase.py", line 178, in **init**
Oct 28 12:20:13 deluge deluged[354]:     version='%(prog)s ' + _get_version_detail(),
Oct 28 12:20:13 deluge deluged[354]:                           ^^^^^^^^^^^^^^^^^^^^^
Oct 28 12:20:13 deluge deluged[354]:   File "/usr/local/lib/python3.11/dist-packages/deluge/argparserbase.py", line 89, in _get_version_detail
Oct 28 12:20:13 deluge deluged[354]:     from deluge._libtorrent import LT_VERSION
Oct 28 12:20:13 deluge deluged[354]:   File "/usr/local/lib/python3.11/dist-packages/deluge/_libtorrent.py", line 24, in <module>
Oct 28 12:20:13 deluge deluged[354]:     import libtorrent as lt
Oct 28 12:20:13 deluge deluged[354]: SystemError: initialization of libtorrent raised unreported exception
Oct 28 12:20:13 deluge systemd[1]: deluged.service: Main process exited, code=exited, status=1/FAILURE
Oct 28 12:20:13 deluge systemd[1]: deluged.service: Failed with result 'exit-code'.
Oct 28 12:20:13 deluge systemd[1]: deluged.service: Scheduled restart job, restart counter is at 5.
Oct 28 12:20:13 deluge systemd[1]: Stopped deluged.service - Deluge Bittorrent Client Daemon.
Oct 28 12:20:13 deluge systemd[1]: deluged.service: Start request repeated too quickly.
Oct 28 12:20:13 deluge systemd[1]: deluged.service: Failed with result 'exit-code'.
Oct 28 12:20:13 deluge systemd[1]: Failed to start deluged.service - Deluge Bittorrent Client Daemon.
```

**Comment by tteck** [comment]
> - Changing Linux distributions without confirming the proper functioning of default settings. 

```
    ____       __               
   / __ \___  / /_  ______ ____ 
  / / / / _ \/ / / / / __ `/ _ \
 / /_/ /  __/ / /_/ / /_/ /  __/
/_____/\___/_/\__,_/\__, /\___/ 
                   /____/       
 
Using Advanced Settings
Using Distribution: debian
Using debian Version: 11
Using Container Type: 1
Using Root Password: Automatic Login
Container ID: 112
Using Hostname: deluge
Using Disk Size: 4
Allocated Cores: 2
Allocated RAM: 2048
Using Bridge: vmbr0
Using IP Address: dhcp
Using Gateway IP Address: Default
Disable IPv6: yes
Using Interface MTU Size: Default
Using DNS Search Domain: Host
Using DNS Server IP Address: Host
Using MAC Address: AE:1A:60:07:B7:59
Using Vlan: Default
Enable Root SSH Access: no
Enable Verbose Mode: no
Creating a Deluge LXC using the above advanced settings
 ✓ Using local for Template Storage.
 ✓ Using local-lvm for Container Storage.
 ✓ Updated LXC Template List
 ✓ LXC Container 112 was successfully created.
 ✓ Started LXC Container
 ✓ Set up Container OS
 ✓ Network Connected: 192.168.86.253 
 ✓ Internet Connected
 ✓ DNS Resolved github.com to 140.82.114.4
 ✓ Updated Container OS
 ✓ Installed Dependencies
 ✓ Updated Python3
 ✓ Installed Deluge
 ✓ Created Service
 ✓ Customized Container
 ✓ Cleaned
 ✓ Completed Successfully!

Deluge should be reachable by going to the following URL.
         http://192.168.86.253:8112 
```

**Comment by tteck** [comment]
Not Debian 12 compatible

**Comment by tteck** [comment]
Deluge is now Debian 12 compatible, with Debian 12 now as default.

**Comment by Drallas** [comment]
Thanks for the quick fix..
