### ISSUE TITLE
Paperless-ngx import script not working

### ISSUE THREAD

**Issue by osswaldo** [tteck/Proxmox#2214]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Hello,
I have an existing paperless-ngx installation running with docker-compose on my old Raspberry Pi. Now I want to move it to my Proxmox server. I made a backup of my existing paperless-ngx data using "docker compose exec -T webserver document_exporter ../export" and copied the backup to new paperless-ngx lxs (installed using the default installer script `bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/paperless-ngx.sh)"`).
Now I want to import the old data. I tried `python3 /opt/paperless/src/documents/management/commands/document_importer.py /root/backup/`, but it doesn't work:

```
Traceback (most recent call last):
  File "/opt/paperless/src/documents/management/commands/document_importer.py", line 9, in <module>
    from django.contrib.auth.models import Permission
  File "/usr/local/lib/python3.11/dist-packages/django/contrib/auth/models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib/python3.11/dist-packages/django/contrib/auth/base_user.py", line 57, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/base.py", line 129, in __new__
    app_config = apps.get_containing_app_config(module)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/apps/registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "/usr/local/lib/python3.11/dist-packages/django/apps/registry.py", line 137, in check_apps_ready
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.11/dist-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.11/dist-packages/django/conf/__init__.py", line 82, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

How can I import the old data?

Thanks a lot!

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions)
