### ISSUE TITLE
Homarr is missing from your scripts!

### ISSUE THREAD

**Issue by realBernieReid** [tteck/Proxmox#2424]
### Please verify that you have read and understood the guidelines.

yes

### A clear and concise description of the issue.

Was reading over some of your prior comments to some others asking, I can't seem to find Homarr in your dashboard listings anymore. Can you take a look at your scripts and see about updating it again?

### Which Linux distribution are you employing?

Default Settings

**Comment by tteck** [comment]
> - For suggestions, questions or feature/script requests, please share them in the [Discussions section.](https://github.com/tteck/Proxmox/discussions) 

## 2023-12-10

### Changed

- **Homarr LXC**
  - Removed, again.

**Comment by realBernieReid** [comment]
Why was it removed?

**Comment by HermesHonshappo** [comment]
> Why was it removed?

Install script is not working. 
Tried to run it in verbose mode and it crashes during yarn build:
```
 ✓ Installed Node.js/Yarn
yarn install v1.22.22
[1/4] Resolving packages...
warning @vitest/coverage-c8@0.33.0: v8 coverage is moved to @vitest/coverage-v8 package
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @nivo/core@0.83.1" has unmet peer dependency "prop-types@>= 15.5.10 < 16.0.0".
warning " > @tiptap/extension-color@2.2.6" has unmet peer dependency "@tiptap/core@^2.0.0".
warning " > @tiptap/extension-highlight@2.2.6" has unmet peer dependency "@tiptap/core@^2.0.0".
warning " > @tiptap/extension-image@2.2.6" has unmet peer dependency "@tiptap/core@^2.0.0".
warning " > @tiptap/extension-link@2.2.6" has unmet peer dependency "@tiptap/core@^2.0.0".
warning " > @tiptap/extension-table@2.2.6" has unmet peer dependency "@tiptap/core@^2.0.0".
warning " > @tiptap/extension-table-cell@2.2.6" has unmet peer dependency "@tiptap/core@^2.0.0".
warning " > @tiptap/extension-table-header@2.2.6" has unmet peer dependency "@tiptap/core@^2.0.0".
warning " > @tiptap/extension-table-row@2.2.6" has unmet peer dependency "@tiptap/core@^2.0.0".
warning " > @tiptap/extension-task-item@2.2.6" has unmet peer dependency "@tiptap/core@^2.0.0".
warning " > @tiptap/extension-task-list@2.2.6" has unmet peer dependency "@tiptap/core@^2.0.0".
warning " > @tiptap/extension-text-align@2.2.6" has unmet peer dependency "@tiptap/core@^2.0.0".
warning " > @tiptap/extension-text-style@2.2.6" has unmet peer dependency "@tiptap/core@^2.0.0".
warning " > @tiptap/extension-underline@2.2.6" has unmet peer dependency "@tiptap/core@^2.0.0".
warning " > @tiptap/react@2.2.6" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "@tiptap/react > @tiptap/extension-floating-menu@2.2.6" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "@tiptap/react > @tiptap/extension-bubble-menu@2.2.6" has unmet peer dependency "@tiptap/core@^2.0.0".
warning " > @vitejs/plugin-react@4.2.1" has unmet peer dependency "vite@^4.2.0 || ^5.0.0".
warning " > next-i18next@14.0.3" has incorrect peer dependency "i18next@^23.4.6".
warning " > next-i18next@14.0.3" has incorrect peer dependency "react-i18next@^13.2.1".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
[1/10] ⠂ better-sqlite3
[2/10] ⠂ cpu-features
[3/10] ⠂ esbuild
[4/10] ⠂ es5-ext
warning Error running install script for optional dependency: "/opt/homarr/node_modules/cpu-features: Command failed.
Exit code: 1
Command: node buildcheck.js > buildcheck.gypi && node-gyp rebuild
Arguments: 
Directory: /opt/homarr/node_modules/cpu-features
Output:
/opt/homarr/node_modules/buildcheck/lib/index.js:115
  throw new Error('Unable to detect compiler type');
  ^

Error: Unable to detect compiler type
    at BuildEnvironment.getKind (/opt/homarr/node_modules/buildcheck/lib/index.js:115:9)
    at BuildEnvironment.tryCompile (/opt/homarr/node_modules/buildcheck/lib/index.js:537:15)
    at BuildEnvironment.checkHeader (/opt/homarr/node_modules/buildcheck/lib/index.js:423:25)
    at Object.<anonymous> (/opt/homarr/node_modules/cpu-features/buildcheck.js:16:4)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
[1/10] ⠐ better-sqlite3
[-/10] ⠐ waiting...
[10/10] ⠐ tree-sitter-yaml
[9/10] ⠐ tree-sitter-json
warning Error running install script for optional dependency: "/opt/homarr/node_modules/tree-sitter-json: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /opt/homarr/node_modules/tree-sitter-json
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0
gyp info using node@20.12.1 | linux | x64
gyp info find Python using Python version 3.11.2 found at \"/usr/bin/python3\"

gyp http GET https://nodejs.org/download/release/v20.12.1/node-v20.12.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v20.12.1/node-v20.12.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v20.12.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v20.12.1/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/opt/homarr/node_modules/tree-sitter-json/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/root/.cache/node-gyp/20.12.1/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/20.12.1',
gyp info spawn args '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/20.12.1/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/opt/homarr/node_modules/tree-sitter-json',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/lib/index.js:16:17)
gyp ERR! stack at which (/usr/lib/node_modules/npm/node_modules/which/lib/index.js:77:9)
gyp ERR! stack at async doWhich (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:112:22)
gyp ERR! stack at async loadConfigGypi (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:77:7)
gyp ERR! stack at async build (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:35:3)
gyp ERR! stack at async run (/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
gyp ERR! System Linux 6.5.13-3-pve
gyp ERR! command \"/usr/bin/node\" \"/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /opt/homarr/node_modules/tree-sitter-json
[1/10] ⠁ better-sqlite3
[-/10] ⠁ waiting...
[10/10] ⠁ tree-sitter-yaml
[-/10] ⠁ waiting...
warning Error running install script for optional dependency: "/opt/homarr/node_modules/tree-sitter: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /opt/homarr/node_modules/tree-sitter
Output:
prebuild-install warn install No prebuilt binaries found (target=20.12.1 runtime=node arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0
gyp info using node@20.12.1 | linux | x64
gyp info find Python using Python version 3.11.2 found at \"/usr/bin/python3\"

gyp http GET https://nodejs.org/download/release/v20.12.1/node-v20.12.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v20.12.1/node-v20.12.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v20.12.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v20.12.1/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/opt/homarr/node_modules/tree-sitter/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/root/.cache/node-gyp/20.12.1/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/20.12.1',
gyp info spawn args '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/20.12.1/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/opt/homarr/node_modules/tree-sitter',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/lib/index.js:16:17)
gyp ERR! stack at which (/usr/lib/node_modules/npm/node_modules/which/lib/index.js:77:9)
gyp ERR! stack at async doWhich (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:112:22)
gyp ERR! stack at async loadConfigGypi (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:77:7)
gyp ERR! stack at async build (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:35:3)
gyp ERR! stack at async run (/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
gyp ERR! System Linux 6.5.13-3-pve
gyp ERR! command \"/usr/bin/node\" \"/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /opt/homarr/node_modules/tree-sitter
gyp ERR! node -v v20.12.1
gyp ERR! node-gyp -v v10.1.0
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "/opt/homarr/node_modules/tree-sitter-yaml: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /opt/homarr/node_modules/tree-sitter-yaml
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0
gyp info using node@20.12.1 | linux | x64
gyp info find Python using Python version 3.11.2 found at \"/usr/bin/python3\"

gyp http GET https://nodejs.org/download/release/v20.12.1/node-v20.12.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v20.12.1/node-v20.12.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v20.12.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v20.12.1/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/opt/homarr/node_modules/tree-sitter-yaml/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/root/.cache/node-gyp/20.12.1/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/20.12.1',
gyp info spawn args '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/20.12.1/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/opt/homarr/node_modules/tree-sitter-yaml',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/lib/index.js:16:17)
gyp ERR! stack at which (/usr/lib/node_modules/npm/node_modules/which/lib/index.js:77:9)
gyp ERR! stack at async doWhich (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:112:22)
gyp ERR! stack at async loadConfigGypi (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:77:7)
gyp ERR! stack at async build (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:35:3)
gyp ERR! stack at async run (/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
gyp ERR! System Linux 6.5.13-3-pve
gyp ERR! command \"/usr/bin/node\" \"/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /opt/homarr/node_modules/tree-sitter-yaml
success Saved lockfile.
Done in 232.04s.
yarn run v1.22.22
$ NEXTAUTH_SECRET=WILL_BE_OVERWRITTEN next build
\- info Loaded env from /opt/homarr/.env
❌ Invalid environment variables: { NEXT_PUBLIC_DEFAULT_COLOR_SCHEME: [ 'Invalid input' ] }
- error Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error

> Build error occurred
Error: Invalid environment variables
    at onValidationError (/opt/homarr/node_modules/@t3-oss/env-core/dist/index.cjs:31:15)
    at Object.createEnv (/opt/homarr/node_modules/@t3-oss/env-core/dist/index.cjs:37:16)
    at createEnv (/opt/homarr/node_modules/@t3-oss/env-nextjs/dist/index.cjs:14:20)
    at Object.<anonymous> (/opt/homarr/src/env.js:25:13)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[ERROR] in line 47: exit code 0: while executing command $STD yarn build
```
