### ISSUE TITLE
Whoogle Helper Issue

### ISSUE THREAD

**Issue by hxii** [tteck/Proxmox#272]
This might be more related to Whoogle specifically, but I'll post this here just in case.

Searching doesn't seem to work and results in the following log output:
```
root@whoogle:~# whoogle-search --host 0.0.0.0        
ERROR:app:Exception on /search [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/app/routes.py", line 79, in decorated
    _ = pickle.load(session_file)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x81 in position 0: ordinal not in range(128)
WARNING:app:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

**Comment by tteck** [comment]
> root@whoogle:~# whoogle-search --host 0.0.0.0

Whoogle should already be running. Just go to the Whoogle LXC IP:5000
![Screenshot 2022-06-08 5 13 55 AM](https://user-images.githubusercontent.com/21342670/172579814-61ba7298-5447-4756-82f0-8f24e3b612e8.png)
Working great here.

**Comment by hxii** [comment]
@tteck I killed and reopened the executable to use the `--debug` flag in order to make sure I see the entire error. Tried to re-install via pip with no luck. I guess I'll try and re-create the LXC.
