### ISSUE TITLE
Can't get both zwavejs2mqtt and zigbee2mqtt LXCs to access respective USB stick at same time

### ISSUE THREAD

**Issue by dimatx** [tteck/Proxmox#305]
Using what I think is vanilla config, but seems like whichever LXC I start first works, and the second one to start is unable to get to the USB device.

**108.conf (zigbee2mqtt)**
```
arch: amd64
cores: 2
features: nesting=1
hostname: zigbee2mqtt
memory: 1024
net0: name=eth0,bridge=vmbr0,gw=192.168.7.1,hwaddr=C6:7E:9B:C5:A6:D7,ip=192.168.7.43/24,type=veth
onboot: 1
ostype: debian
rootfs: local-lvm:vm-108-disk-0,size=4G
swap: 512
lxc.cgroup2.devices.allow: a
lxc.cap.drop:
lxc.cgroup2.devices.allow: c 188:* rwm
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.mount.entry: /dev/serial/by-id  dev/serial/by-id  none bind,optional,create=dir
lxc.mount.entry: /dev/ttyUSB0       dev/ttyUSB0       none bind,optional,create=file
lxc.mount.entry: /dev/ttyACM0       dev/ttyACM0       none bind,optional,create=file
```

**108.conf (zwavejs2mqtt)**
```
arch: amd64
cores: 2
features: nesting=1
hostname: zwavejs2mqtt
memory: 1024
net0: name=eth0,bridge=vmbr0,gw=192.168.7.1,hwaddr=9A:52:2D:C1:93:43,ip=192.168.7.42/24,type=veth
onboot: 1
ostype: debian
rootfs: local-lvm:vm-105-disk-0,size=4G
swap: 512
lxc.cgroup2.devices.allow: a
lxc.cap.drop:
lxc.cgroup2.devices.allow: c 188:* rwm
lxc.cgroup2.devices.allow: c 189:* rwm
lxc.mount.entry: /dev/serial/by-id  dev/serial/by-id  none bind,optional,create=dir
lxc.mount.entry: /dev/ttyUSB0       dev/ttyUSB0       none bind,optional,create=file
lxc.mount.entry: /dev/ttyACM0       dev/ttyACM0       none bind,optional,create=file
lxc.mount.entry: /dev/ttyACM1       dev/ttyACM1       none bind,optional,create=file
```

**lsusb on proxmox host**
```
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 8087:0a2b Intel Corp. Bluetooth wireless interface
Bus 001 Device 003: ID 0658:0200 Sigma Designs, Inc. Aeotec Z-Stick Gen5 (ZW090) - UZB
Bus 001 Device 006: ID 1cf1:0030 Dresden Elektronik ZigBee gateway [ConBee II]
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**ls -l /dev/serial/by-id (same on both LXCs)**
`total 0
lrwxrwxrwx 1 root root 13 Jun 27 23:00 usb-0658_0200-if00 -> ../../ttyACM1
lrwxrwxrwx 1 root root 13 Jun 28 00:00 usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2253440-if00 -> ../../ttyACM0`

**zigbee configuration.yaml excerpt**
```
serial:
  port: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2253440-if00
  adapter: deconz
```

**error when zigbee2mqtt is started after zwavejs2mqtt**
```
root@zigbee2mqtt:~# cd /opt/zigbee2mqtt/
root@zigbee2mqtt:/opt/zigbee2mqtt# npm start

> zigbee2mqtt@1.25.2 start
> node index.js

Zigbee2MQTT:info  2022-06-28 00:38:09: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2022-06-28.00-38-09' filename: log.txt
Zigbee2MQTT:info  2022-06-28 00:38:09: Starting Zigbee2MQTT version 1.25.2 (commit #9b2a9210)
Zigbee2MQTT:info  2022-06-28 00:38:09: Starting zigbee-herdsman (0.14.34)
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2022-06-28 00:38:09: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-06-28 00:38:09: Failed to start zigbee
Zigbee2MQTT:error 2022-06-28 00:38:09: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-06-28 00:38:09: Exiting...
Zigbee2MQTT:error 2022-06-28 00:38:09: Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/driver/driver.ts:182:28)
    at SerialPort._error (/opt/zigbee2mqtt/node_modules/@serialport/stream/lib/index.js:198:14)
    at /opt/zigbee2mqtt/node_modules/@serialport/stream/lib/index.js:242:12
```

**Comment by dimatx** [comment]
Was able to resolve this by commenting out the default lxc.mount and using:

 `lxc.mount.entry: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2253440-if00  dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2253440-if00 none bind,optional,create=file` 
and 
`lxc.mount.entry: /dev/serial/by-id/usb-0658_0200-if00 dev/serial/by-id/usb-0658_0200-if00 none bind,optional,create=file `
respectively.
