### ISSUE TITLE
Home Assistant Core LXC cant complete

### ISSUE THREAD

**Issue by Jdemuren** [tteck/Proxmox#592]
runinng the script cd /srv/homeassistant && python3 -m venv . && source bin/activate && hass in the LXC console keeps giving error below;

homeassistant-core login: root (automatic login)

root@homeassistant-core:~# cd /srv/homeassistant && python3 -m venv . && source bin/activate && hass
Unable to find configuration. Creating default one in /root/.homeassistant
ERROR: Cannot set filter: libpcap is not available. Cannot compile filter !
2022-10-02 16:41:57.310 ERROR (SyncWorker_0) [scapy.runtime] Cannot set filter: libpcap is not available. Cannot compile filter !
2022-10-02 16:41:57.400 ERROR (SyncWorker_0) [homeassistant.components.dhcp] Cannot watch for dhcp packets without a functional packet filter: libpcap is not available. Cannot compile filter !
2022-10-02 16:42:13.385 ERROR (MainThread) [haffmpeg.core] FFmpeg fails [Errno 2] No such file or directory: 'ffmpeg'
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/haffmpeg/core.py", line 136, in open
    self._proc = await self._loop.run_in_executor(None, proc_func)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
2022-10-02 16:42:13.389 WARNING (MainThread) [haffmpeg.tools] Error starting FFmpeg.
2022-10-02 16:42:48.839 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection
2022-10-02 16:42:48.841 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connection

Thanks

**Comment by tteck** [comment]
Reboot LXC and go to IP:8123

**Comment by Jdemuren** [comment]
I did but the script didn't fully run, so I have the basic home assistant not the core. I will start again after installing from pve console I will reboot and run the script again.

**Comment by tteck** [comment]
Home Assistant Core is exactly what it states. No supervisor which means no add-on's.

**Comment by tteck** [comment]
It's the same as Home Assistant Container, but runs in a python virtual environment (venv).

**Comment by Jdemuren** [comment]
Oh ok. Thanks for the clarification

**Comment by tteck** [comment]
https://www.home-assistant.io/installation/#compare-installation-methods
