### ISSUE TITLE
Zigbee2MQTT v5 script : ‼ ERROR 1@347 Unknown failure occurred.

### ISSUE THREAD

**Issue by schiz0phr3ne** [tteck/Proxmox#939]
**Describe the issue**
I can't update Zigbee2MQTT with v5 script (and even with older method).

**Screenshots**
```
user@zigbee2mqtt:/opt/zigbee2mqtt# bash -x -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/zigbee2mqtt-v5.sh)"
+ header_info
+ cat
 _____   _       __             ___   __  _______  ____________
/__  /  (_)___ _/ /_  ___  ___ |__ \ /  |/  / __ \/_  __/_  __/
  / /  / / __  / __ \/ _ \/ _ \__/ // /|_/ / / / / / /   / /   
 / /__/ / /_/ / /_/ /  __/  __/ __// /  / / /_/ / / /   / /    
/____/_/\__, /_.___/\___/\___/____/_/  /_/\___\_\/_/   /_/     
   v5  /____/ 🐝
 
+ cd /opt/zigbee2mqtt
+ msg_info 'Checking for Backup Directory'
+ local 'msg=Checking for Backup Directory'
+ echo -ne ' - \033[33mChecking for Backup Directory...'
 - Checking for Backup Directory...+ '[' -d data-backup ']'
+ msg_ok 'No Backup Directory Exists'
+ local 'msg=No Backup Directory Exists'
+ echo -e '\r\033[K \033[1;92m✓\033[m \033[1;92mNo Backup Directory Exists\033[m'
 ✓ No Backup Directory Exists
+ msg_info 'Stopping Zigbee2MQTT'
+ local 'msg=Stopping Zigbee2MQTT'
+ echo -ne ' - \033[33mStopping Zigbee2MQTT...'
 - Stopping Zigbee2MQTT...+ systemctl stop zigbee2mqtt
+ msg_ok 'Stopped Zigbee2MQTT'
+ local 'msg=Stopped Zigbee2MQTT'
+ echo -e '\r\033[K \033[1;92m✓\033[m \033[1;92mStopped Zigbee2MQTT\033[m'
 ✓ Stopped Zigbee2MQTT
+ msg_info 'Creating Backup of Configuration'
+ local 'msg=Creating Backup of Configuration'
+ echo -ne ' - \033[33mCreating Backup of Configuration...'
 - Creating Backup of Configuration...+ cp -R data data-backup
+ msg_ok 'Created Backup of Configuration'
+ local 'msg=Created Backup of Configuration'
+ echo -e '\r\033[K \033[1;92m✓\033[m \033[1;92mCreated Backup of Configuration\033[m'
 ✓ Created Backup of Configuration
+ msg_info 'Updating Zigbee2MQTT'
+ local 'msg=Updating Zigbee2MQTT'
+ echo -ne ' - \033[33mUpdating Zigbee2MQTT...'
 - Updating Zigbee2MQTT...+ git pull
++ EXIT=1
++ LINE=347
++ error_exit
++ trap - ERR
++ local 'reason=Unknown failure occurred.'
++ local 'msg=Unknown failure occurred.'
++ local 'flag=\033[01;31m‼ ERROR \033[m1@347'
++ echo -e '\033[01;31m‼ ERROR \033[m1@347 Unknown failure occurred.'
‼ ERROR 1@347 Unknown failure occurred.
++ exit 1
```

**Comment by tteck** [comment]
https://github.com/tteck/Proxmox/blob/f351e7ef54ac749b2ff527409d4b6e4bb738f836/ct/zigbee2mqtt-v5.sh#L347

Do you have `git` installed?

**Comment by schiz0phr3ne** [comment]
Yes

```
user@zigbee2mqtt:/opt/zigbee2mqtt# apt list --installed git
Listing... Done
git/stable,now 1:2.30.2-1 amd64 [installed]
```

EDIT : no problem with firewall, nothing blocked.

**Comment by tteck** [comment]
`cd /opt/zigbee2mqtt && bash update.sh` doesn't work either?

What does `git status` show?

```
root@zigbee2mqtt:/opt/zigbee2mqtt# git status                           
On branch dev
Your branch is up to date with 'origin/dev'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   data/configuration.yaml

no changes added to commit (use "git add" and/or "git commit -a")
root@zigbee2mqtt:/opt/zigbee2mqtt# 
```

**Comment by schiz0phr3ne** [comment]
```
user@zigbee2mqtt:/opt/zigbee2mqtt# cd /opt/zigbee2mqtt && bash update.sh
Stopping Zigbee2MQTT...
Creating backup of configuration...
Updating...
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Updating dddce571..bb3e8f6d
error: Your local changes to the following files would be overwritten by merge:
        package-lock.json
Please commit your changes or stash them before you merge.
Aborting
Installing dependencies...

added 752 packages, and audited 753 packages in 6s

67 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Restore configuration...
Starting Zigbee2MQTT...
Done!
```

But after that, I'm always in current version (`1.29.0`).

Maybe this is the problem ?
```
error: Your local changes to the following files would be overwritten by merge:
        package-lock.json
Please commit your changes or stash them before you merge.
```

And `git status` :
```
root@zigbee2mqtt:/opt/zigbee2mqtt# git status
On branch master
Your branch is behind 'origin/master' by 7 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   data/configuration.yaml
        modified:   package-lock.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        data/.configuration.yaml.swp

no changes added to commit (use "git add" and/or "git commit -a")
```

I didn't remember any manuel change in `package-lock.json`.

**Comment by tteck** [comment]
`git stash` then update

**Comment by schiz0phr3ne** [comment]
OK, I'm not a `git` guru, so thank you for this → I can update.

But now, I can't access Z2M anymore : there is nothing listening on port 9442.

```
user@zigbee2mqtt:~# service zigbee2mqtt status
* zigbee2mqtt.service - zigbee2mqtt
     Loaded: loaded (/etc/systemd/system/zigbee2mqtt.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-01-13 23:33:45 CET; 7s ago
   Main PID: 361 (npm start)
      Tasks: 23 (limit: 76961)
     Memory: 95.2M
        CPU: 1.603s
     CGroup: /system.slice/zigbee2mqtt.service
             |-361 npm start
             |-372 sh -c -- node index.js
             `-373 node index.js

Jan 13 23:33:45 zigbee2mqtt systemd[1]: Started zigbee2mqtt.
Jan 13 23:33:45 zigbee2mqtt npm[361]: > zigbee2mqtt@1.29.2 start
Jan 13 23:33:45 zigbee2mqtt npm[361]: > node index.js
Jan 13 23:33:46 zigbee2mqtt npm[373]: Zigbee2MQTT:info  2023-01-13 23:33:46: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2023-01-13.23>
Jan 13 23:33:46 zigbee2mqtt npm[373]: Zigbee2MQTT:info  2023-01-13 23:33:46: Starting Zigbee2MQTT version 1.29.2 (commit #bb3e8f6d)
Jan 13 23:33:46 zigbee2mqtt npm[373]: Zigbee2MQTT:info  2023-01-13 23:33:46: Starting zigbee-herdsman (0.14.83-hotfix.0)
user@zigbee2mqtt:~# ss -tunlp
Netid      State       Recv-Q      Send-Q           Local Address:Port           Peer Address:Port      Process                                         
udp        UNCONN      0           0                127.0.0.53%lo:53                  0.0.0.0:*          users:(("systemd-resolve",pid=119,fd=17))      
udp        UNCONN      0           0                      0.0.0.0:5355                0.0.0.0:*          users:(("systemd-resolve",pid=119,fd=11))      
udp        UNCONN      0           0                         [::]:5355                   [::]:*          users:(("systemd-resolve",pid=119,fd=13))      
tcp        LISTEN      0           4096                   0.0.0.0:5355                0.0.0.0:*          users:(("systemd-resolve",pid=119,fd=12))      
tcp        LISTEN      0           4096                 127.0.0.1:6060                0.0.0.0:*          users:(("crowdsec",pid=206,fd=23))             
tcp        LISTEN      0           4096             127.0.0.53%lo:53                  0.0.0.0:*          users:(("systemd-resolve",pid=119,fd=18))      
tcp        LISTEN      0           100                  127.0.0.1:25                  0.0.0.0:*          users:(("master",pid=344,fd=13))               
tcp        LISTEN      0           4096                      [::]:5355                   [::]:*          users:(("systemd-resolve",pid=119,fd=14))      
tcp        LISTEN      0           4096                         *:22                        *:*          users:(("systemd",pid=1,fd=45))                
tcp        LISTEN      0           100                      [::1]:25                     [::]:*          users:(("master",pid=344,fd=14))
```

I don't thing that is related to you and your scripts, and I have a backup.

**Comment by tteck** [comment]
Maybe crowdsec is the issue?

**Comment by schiz0phr3ne** [comment]
I think I have a problem to access to my adapter (no problem with the backup) :
```
user@zigbee2mqtt:/opt/zigbee2mqtt# npm start

> zigbee2mqtt@1.29.2 start
> node index.js

Zigbee2MQTT:info  2023-01-13 23:48:07: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2023-01-13.23-48-07' filename: log.txt
Zigbee2MQTT:info  2023-01-13 23:48:07: Starting Zigbee2MQTT version 1.29.2 (commit #bb3e8f6d)
Zigbee2MQTT:info  2023-01-13 23:48:07: Starting zigbee-herdsman (0.14.83-hotfix.0)
Zigbee2MQTT:error 2023-01-13 23:48:07: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-01-13 23:48:07: Failed to start zigbee
Zigbee2MQTT:error 2023-01-13 23:48:07: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-01-13 23:48:07: Exiting...
Zigbee2MQTT:error 2023-01-13 23:48:07: Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/opt/zigbee2mqtt/node_modules/@serialport/stream/dist/index.js:76:22)
    at /opt/zigbee2mqtt/node_modules/@serialport/stream/dist/index.js:112:18
user@zigbee2mqtt:/opt/zigbee2mqtt# service zigbee2mqtt stop
user@zigbee2mqtt:/opt/zigbee2mqtt# npm start

> zigbee2mqtt@1.29.2 start
> node index.js

Zigbee2MQTT:info  2023-01-13 23:50:24: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2023-01-13.23-50-24' filename: log.txt
Zigbee2MQTT:info  2023-01-13 23:50:24: Starting Zigbee2MQTT version 1.29.2 (commit #bb3e8f6d)
Zigbee2MQTT:info  2023-01-13 23:50:24: Starting zigbee-herdsman (0.14.83-hotfix.0)
Zigbee2MQTT:error 2023-01-13 23:50:44: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-01-13 23:50:44: Failed to start zigbee
Zigbee2MQTT:error 2023-01-13 23:50:44: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-01-13 23:50:44: Exiting...
Zigbee2MQTT:error 2023-01-13 23:50:44: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/opt/zigbee2mqtt/lib/zigbee.ts:58:27)
    at Controller.start (/opt/zigbee2mqtt/lib/controller.ts:101:27)
    at start (/opt/zigbee2mqtt/index.js:107:5)
```

I think I will go to bed now (long week ; near midnight at home), and see tomorrow.
I close this issue, as the remaining problem is not from your side.

Thank you @tteck for your help.

**Comment by schiz0phr3ne** [comment]
I had a dot file for the `configuration.yaml` and a process that wrote in the file.
Everything is fine now.

![image](https://user-images.githubusercontent.com/22858496/212436890-b97bcd72-cf63-42a2-9a76-6066d8473249.png)

Go to bed now :D

**Comment by nortuzar** [comment]
> I had a dot file for the `configuration.yaml` and a process that wrote in the file. Everything is fine now.
> 
> ![image](https://user-images.githubusercontent.com/22858496/212436890-b97bcd72-cf63-42a2-9a76-6066d8473249.png)
> 
> Go to bed now :D

Hi @schiz0phr3ne , im having the same problem but I didnt understand your comment/solution
_I had a dot file for the configuration.yaml and a process that wrote in the file._

Could you explain in a different way how you fix it? Thanks!

**Comment by schiz0phr3ne** [comment]
Hi @nortuzar,

Did you check if your `configuration.yaml` is actualy written by `root` ?
- Open the file with `nano` for example
- If message `File configuration.yaml is being edited by root` appears in `nano`, then you have same problem than me
- Save the file elsewhere with `nano` to make a backup
- Check in `Z2M` folder, with `ls -la` command, if you have a `configuration.yaml` file starting with a dot : `.configuration.yaml.swp`
- If you have this dot file, delete it
- Then you should be able to edit correctly your configuration file, and make the upgrade

**Comment by nortuzar** [comment]
@schiz0phr3ne , i don't know what to say. But before making the post, I restore an old version, the 1.28. Then I use the script v.5 to update and all work perfect.....

Anyway, hopefully this could help other people

Thanks for the quick reply!
