### ISSUE TITLE
deluged daemon not starting

### ISSUE THREAD

**Issue by bstory2001** [tteck/Proxmox#947]
**Describe the issue**
The web-ui service starts and I can connect to it through web browser.  Though the daemon does not start when clicking 'Start Daemon', or when attempting to start it in the Console. Output belose is of systemctl status deluged and journalctl

I fixed it by installing libtorrent package:
`root@deluge: pip install lbry-libtorrent`

**Screenshots**
![image](https://user-images.githubusercontent.com/3096500/212868993-86e6d3c1-2a05-4d98-af86-1264a261e730.png)

```
root@deluge:/usr/local/bin# journalctl _PID=313
-- Journal begins at Tue 2023-01-17 09:04:07 UTC, ends at Tue 2023-01-17 09:58:09 UTC. --
Jan 17 09:58:08 deluge deluged[313]: Traceback (most recent call last):
Jan 17 09:58:08 deluge deluged[313]:   File "/usr/local/lib/python3.9/dist-packages/deluge/_libtorrent.py", line 21, in <modul>
Jan 17 09:58:08 deluge deluged[313]:     import deluge.libtorrent as lt
Jan 17 09:58:08 deluge deluged[313]: ModuleNotFoundError: No module named 'deluge.libtorrent'
Jan 17 09:58:08 deluge deluged[313]: During handling of the above exception, another exception occurred:
Jan 17 09:58:08 deluge deluged[313]: Traceback (most recent call last):
Jan 17 09:58:08 deluge deluged[313]:   File "/usr/local/lib/python3.9/dist-packages/deluge/_libtorrent.py", line 24, in <modul>
Jan 17 09:58:08 deluge deluged[313]:     import libtorrent as lt
Jan 17 09:58:08 deluge deluged[313]: ModuleNotFoundError: No module named 'libtorrent'
Jan 17 09:58:08 deluge deluged[313]: During handling of the above exception, another exception occurred:
Jan 17 09:58:08 deluge deluged[313]: Traceback (most recent call last):
Jan 17 09:58:08 deluge deluged[313]:   File "/usr/local/bin/deluged", line 8, in <module>
Jan 17 09:58:08 deluge deluged[313]:     sys.exit(start_daemon())
Jan 17 09:58:08 deluge deluged[313]:   File "/usr/local/lib/python3.9/dist-packages/deluge/core/daemon_entry.py", line 87, in >
Jan 17 09:58:08 deluge deluged[313]:     from deluge.core.daemon import is_daemon_running
Jan 17 09:58:08 deluge deluged[313]:   File "/usr/local/lib/python3.9/dist-packages/deluge/core/daemon.py", line 19, in <modul>
Jan 17 09:58:08 deluge deluged[313]:     from deluge.core.core import Core
Jan 17 09:58:08 deluge deluged[313]:   File "/usr/local/lib/python3.9/dist-packages/deluge/core/core.py", line 26, in <module>
Jan 17 09:58:08 deluge deluged[313]:     from deluge._libtorrent import LT_VERSION, lt
Jan 17 09:58:08 deluge deluged[313]:   File "/usr/local/lib/python3.9/dist-packages/deluge/_libtorrent.py", line 26, in <modul>
Jan 17 09:58:08 deluge deluged[313]:     raise LibtorrentImportError('No libtorrent library found: %s' % (ex))
Jan 17 09:58:08 deluge deluged[313]: deluge.error.LibtorrentImportError: No libtorrent library found: No module named 'libtorr>
lines 1-23...skipping...
-- Journal begins at Tue 2023-01-17 09:04:07 UTC, ends at Tue 2023-01-17 09:58:09 UTC. --
Jan 17 09:58:08 deluge deluged[313]: Traceback (most recent call last):
Jan 17 09:58:08 deluge deluged[313]:   File "/usr/local/lib/python3.9/dist-packages/deluge/_libtorrent.py", line 21, in <module>
Jan 17 09:58:08 deluge deluged[313]:     import deluge.libtorrent as lt
Jan 17 09:58:08 deluge deluged[313]: ModuleNotFoundError: No module named 'deluge.libtorrent'
Jan 17 09:58:08 deluge deluged[313]: During handling of the above exception, another exception occurred:
Jan 17 09:58:08 deluge deluged[313]: Traceback (most recent call last):
Jan 17 09:58:08 deluge deluged[313]:   File "/usr/local/lib/python3.9/dist-packages/deluge/_libtorrent.py", line 24, in <module>
Jan 17 09:58:08 deluge deluged[313]:     import libtorrent as lt
Jan 17 09:58:08 deluge deluged[313]: ModuleNotFoundError: No module named 'libtorrent'
Jan 17 09:58:08 deluge deluged[313]: During handling of the above exception, another exception occurred:
Jan 17 09:58:08 deluge deluged[313]: Traceback (most recent call last):
Jan 17 09:58:08 deluge deluged[313]:   File "/usr/local/bin/deluged", line 8, in <module>
Jan 17 09:58:08 deluge deluged[313]:     sys.exit(start_daemon())
Jan 17 09:58:08 deluge deluged[313]:   File "/usr/local/lib/python3.9/dist-packages/deluge/core/daemon_entry.py", line 87, in start_daemon
Jan 17 09:58:08 deluge deluged[313]:     from deluge.core.daemon import is_daemon_running
Jan 17 09:58:08 deluge deluged[313]:   File "/usr/local/lib/python3.9/dist-packages/deluge/core/daemon.py", line 19, in <module>
Jan 17 09:58:08 deluge deluged[313]:     from deluge.core.core import Core
Jan 17 09:58:08 deluge deluged[313]:   File "/usr/local/lib/python3.9/dist-packages/deluge/core/core.py", line 26, in <module>
Jan 17 09:58:08 deluge deluged[313]:     from deluge._libtorrent import LT_VERSION, lt
Jan 17 09:58:08 deluge deluged[313]:   File "/usr/local/lib/python3.9/dist-packages/deluge/_libtorrent.py", line 26, in <module>
Jan 17 09:58:08 deluge deluged[313]:     raise LibtorrentImportError('No libtorrent library found: %s' % (ex))
Jan 17 09:58:08 deluge deluged[313]: deluge.error.LibtorrentImportError: No libtorrent library found: No module named 'libtorrent'
```

**Comment by tteck** [comment]
Thank you!
Added to script
